- build.gradle
- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/dto/RequestMemberDto.java
- src/main/java/ssafy/lambda/vote/dto/RequestVoteDto.java
- src/main/java/ssafy/lambda/vote/entity/ExpiredVote.java
- src/main/java/ssafy/lambda/vote/entity/Vote.java
- src/main/java/ssafy/lambda/vote/entity/VoteInfo.java
- src/main/java/ssafy/lambda/vote/entity/VoteItem.java
- src/main/java/ssafy/lambda/vote/repository/VoteInfoRepository.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepository.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
- src/main/resources/application.yml
* Vote관련 Entity, Repository, Service, Controller 구현 : vote(C), vote_info(C)
* dependencies(Querydsl, swagger, p6spy) 추가 
* @RequestHeader로 받은 Authorization의 값으로 어떻게 MEMBER를 확인할 수 있을까요?
> Vote관련 Create 작업 및 dependencies 추가

- build.gradle
- src/main/java/ssafy/lambda/member/controller/MemberController.java
- src/main/java/ssafy/lambda/member/dto/RequestMemberDto.java
- src/main/java/ssafy/lambda/member/dto/ResponseMemberDto.java
- src/main/java/ssafy/lambda/member/entity/Member.java
- src/main/java/ssafy/lambda/member/repository/MemberRepository.java
- src/main/java/ssafy/lambda/member/service/MemberService.java
- src/main/java/ssafy/lambda/membership/controller/MembershipController.java
- src/main/java/ssafy/lambda/membership/dto/RequestMembershipDto.java
- src/main/java/ssafy/lambda/membership/dto/ResponseMembershipDto.java
- src/main/java/ssafy/lambda/membership/repository/MembershipRepository.java
- src/main/java/ssafy/lambda/membership/service/MembershipService.java
- src/main/java/ssafy/lambda/team/controller/TeamController.java
- src/main/java/ssafy/lambda/team/dto/RequestTeamDto.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamDto.java
- src/main/java/ssafy/lambda/team/entity/Team.java
- src/main/java/ssafy/lambda/team/repository/TeamRepository.java
- src/main/java/ssafy/lambda/team/service/TeamService.java
* http response 추가
* Entity 접근 제어자 수정
* Lazy Fetch로 인한 findAll 에러 수정
* Membership Entity에 Controller와 Service 추가
* 임시 DTO 추가
* 스웨거 추가
* API 네이밍 괜찮을까요?
> Membership Entity에 Controller와 Service 추가, API 전체적인 수정, 스웨거 추가

- src/main/java/ssafy/lambda/membership/repository/MembershipRepository.java
- src/main/java/ssafy/lambda/membership/service/MembershipService.java
MemberId, TeamId 로 Membership 찾기 추가
예외 메세지의 통일이 필요할것 같습니다.
> feat: MemberId, TeamId 로 Membership 찾기 추가

- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/dto/ResponseCommentDto.java
- src/main/java/ssafy/lambda/vote/entity/Vote.java
- src/main/java/ssafy/lambda/vote/entity/VoteComment.java
- src/main/java/ssafy/lambda/vote/repository/CommentRepository.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryCustom.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
Issue : #21 #22 
- 기존 VoteServiceImpl과 VoteRepositoryImpl 코드 수정
- 댓글 엔티티, CRD기능 구현
1. 댓글 수정 기능이 필요할까요?
2. memberService와 teamService의 findById 메서드 호출에 대한 논의가 필요합니다
3. Vote 서비스가 커짐에 따라 도메인 분리의 필요성을 느끼고 있습니다
> feat: VoteComment 기능 구현

- src/main/java/ssafy/lambda/member/repository/MemberRepository.java
- src/main/java/ssafy/lambda/team/repository/TeamRepository.java
- findAllByTeamId와 findAllByMemberId 수정
- 따로 없습니다!
> Member와 Team 기능 수정

- src/main/java/ssafy/lambda/board/entity/ExpiredVote.java
- src/main/java/ssafy/lambda/vote/entity/Vote.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
이슈 : #49 
- Vote, ExpiredVote 엔티티에서 isProceeding 필드를 삭제
- isProceeding 필드 삭제로 인한 해당 필드 사용 메서드 변경 및 삭제
> Vote, ExpiredVote isProceeding 필드 삭제

- src/main/java/ssafy/lambda/member/controller/MemberController.java
- src/main/java/ssafy/lambda/member/dto/ResponseMemberDto.java
- src/main/java/ssafy/lambda/member/repository/MemberRepository.java
- src/main/java/ssafy/lambda/member/service/MemberService.java
- src/main/java/ssafy/lambda/member/service/MemberServiceImpl.java
> Member 도메인 수정 및 기능추가

- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
이슈 : #60 #62 
- Vote 도메인 내 필요없는 변수들 삭제
- VoteController의 @RequestParam, @PathVariable의 name을 명시
- 투표 시 VoteInfoId를 반환하도록 로직 추가
> Vote 도메인 리팩토링 및 기능 추가

- src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
> feat: invitation 초대 생성 배열로 변경

- src/main/java/ssafy/lambda/LambdaApplication.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamVoteWhetherDto.java
- src/main/java/ssafy/lambda/team/service/TeamWithVoteService.java
- src/main/java/ssafy/lambda/team/service/TeamWithVoteServiceImpl.java
- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/dto/RequestReviewDto.java
- src/main/java/ssafy/lambda/vote/dto/RequestVoteDto.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryCustom.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
- HTTP Create시 URI 반환을 위한 설정 추가
- 투표 생성 시 이미지를 받고 저장하기 위한 로직 추가
- 리뷰 작성 시 필요한 데이터들 DTO로 묶어서 관리
- 투표 여부에 따른 팀 반환 메서드 개발
- 투표 여부에 따른 팀 반환 메서드를 TeamWithVoteService로 Team과 Vote Service로 
나누어서 각각의 필요한 메서드를 호출하고자 했습니다.
- 다만, 투표 여부에 대한 쿼리 최적화 과정에서 굳이 나눌 필요 없이 Team에서 수행해도 될 것 같다는 생각이 들었습니다.
- 일단은 vote branch에서 작업 중인 내용이었기 때문에 이에 관해 voteService와 voteRepository에서 해당 로직을 구현하였지만, 
통합할 때 이를 Team으로 옮기고자 합니다. 
- 이에 대한 좋은 의견이 있으신가요?
> 투표 생성 시 이미지 추가 및 팀 반환 로직 개발

- src/main/java/ssafy/lambda/board/controller/BoardController.java
- src/main/java/ssafy/lambda/board/dto/MemberWithPercenCntDto.java
- src/main/java/ssafy/lambda/board/dto/ResponseBoardDetailDto.java
- src/main/java/ssafy/lambda/board/dto/ResponseBoardSummaryDto.java
- src/main/java/ssafy/lambda/board/dto/ResponseCommentDto.java
- src/main/java/ssafy/lambda/board/entity/BoardComment.java
- src/main/java/ssafy/lambda/board/repository/BoardRepositoryCustom.java
- src/main/java/ssafy/lambda/board/repository/CommentRepository.java
- src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepository.java
- src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepositoryImpl.java
- src/main/java/ssafy/lambda/board/service/BoardService.java
- src/main/java/ssafy/lambda/board/service/BoardServiceImpl.java
- src/main/java/ssafy/lambda/global/response/ApiError.java
이슈 : #63 
- Board 도메인 내 comment(댓글) 기능 수정
- Board 도메인 내 board(만료된 투표 정보) 기능 개발
- 데이터가 적어 page 기능의 테스트가 미흡한 상태
- 추가 에러 사항 발견하면 말씀해주세요!
> Board 도메인 수정 및 개발

- src/main/java/ssafy/lambda/global/response/ApiError.java
- src/main/java/ssafy/lambda/point/NotEnoughPointException.java
- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/exception/VoteInfoNotFoundException.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
이슈 : #71
사용해보시고 수정해야할 사항이 있으면 말씀해주세요!
> [Vote] 포인트 사용 서비스 개발 및 예외처리

- src/main/java/ssafy/lambda/membership/repository/MembershipRepository.java
- 왜인지 모르겠지만 저는 @Param이 없는 상태로는 예외가 발생하였습니다.
- 없어도 예외가 안나시는 분들이 계신대 이유를 아시는 분..?
> fix: @Param 추가

- src/main/java/ssafy/lambda/member/controller/MemberController.java
> fix: member 찾기 이메일 -> 태그 변경

- src/main/java/ssafy/lambda/invitation/service/InvitationServiceImpl.java
초대시 초대를 받은 사람에게 알림을 생성하는 기능을 추가했습니다.
> feat: invitation 초대시 알림 생성

- src/main/java/ssafy/lambda/LambdaApplication.java
- src/main/java/ssafy/lambda/board/entity/BoardComment.java
- src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
- src/main/java/ssafy/lambda/invitation/service/InvitationServiceImpl.java
- src/main/java/ssafy/lambda/member/controller/MemberController.java
- src/main/java/ssafy/lambda/team/controller/TeamController.java
- src/main/java/ssafy/lambda/team/dto/RequestTeamCreateDto.java
- src/main/java/ssafy/lambda/team/dto/RequestTeamUpdateDto.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamDto.java
- src/main/java/ssafy/lambda/team/entity/Team.java
- src/main/java/ssafy/lambda/team/service/TeamService.java
- src/main/java/ssafy/lambda/team/service/TeamServiceImpl.java
- 그룹 생성 페이지를 위해 team 관련 api의 로직을 수정했습니다
- 사용 안하는 api 주석처리했습니다
- 에러 발생시 말해주세요!
> fix: team 관련 api 수정

- src/main/java/ssafy/lambda/membership/controller/MembershipController.java
- src/main/java/ssafy/lambda/membership/dto/ResponseMembershipDto.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamGetDto.java
profileImgUrl를 ResponseMembershipDto에 추가
추가 정보 추가하였습니다.
> fix: profileImgUrl를 ResponseMembershipDto에 추가

- src/main/java/ssafy/lambda/invitation/entity/Invitation.java
- src/main/java/ssafy/lambda/team/controller/TeamController.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamGetDto.java
- src/main/java/ssafy/lambda/team/dto/ResponseTeamVoteWhetherDto.java
- src/main/java/ssafy/lambda/team/entity/Team.java
- src/main/java/ssafy/lambda/team/service/TeamWithVoteServiceImpl.java
#58 
팀을 나갔을때 알림들을 삭제하도록 추가했습니다.
GET /team API 에서 투표가 남았는지 여부를 추가해서 반환하도록 했습니다.
> Team API 수정 

- src/main/java/ssafy/lambda/accesstoken/controller/AccessTokenController.java
- src/main/java/ssafy/lambda/accesstoken/service/AccessTokenService.java
- src/main/java/ssafy/lambda/global/config/SecurityConfig.java
- src/main/java/ssafy/lambda/member/dto/ResponseMemberDto.java
- src/main/java/ssafy/lambda/member/service/MemberService.java
- src/main/java/ssafy/lambda/member/service/MemberServiceImpl.java
개발용 로그인 수정 
개발용이기 때문에 완성 후 삭제될 예정입니다!
> 개발용 로그인 수정

- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/service/VoteService.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
teamId를 사용하는 로직을 teamName으로 수정하였습니다.
> [Vote] teamId 사용 로직 teamName으로 수정

- src/main/java/ssafy/lambda/global/common/TimeManager.java
- src/main/java/ssafy/lambda/global/exception/GlobalExceptionHandler.java
- src/main/java/ssafy/lambda/notification/dto/ResponseNotificationDto.java
- src/main/java/ssafy/lambda/notification/service/NotificationServiceImpl.java
- src/main/java/ssafy/lambda/team/controller/TeamController.java
- src/main/java/ssafy/lambda/team/repository/TeamRepository.java
알림 리스트를 반환할때 알림의 생성 시간을 반환하도록 추가했습니다.
> Notification 알림 리스트 시간 반환 추가

- src/main/java/ssafy/lambda/board/controller/BoardController.java
- src/main/java/ssafy/lambda/board/service/BoardService.java
- src/main/java/ssafy/lambda/board/service/BoardServiceImpl.java
- 만료된 투표에 대해 teamId 사용 로직을 teamName으로 변경하였습니다.
- 또한, PathVariable 사용에서 RequestParam을 사용하도록 변경하였습니다.
확인바랍니다!
> [ExpiredVote] teamId -> teamName으로 로직 변경 및 수정

- src/main/java/ssafy/lambda/board/entity/ExpiredVote.java
- src/main/java/ssafy/lambda/invitation/entity/Invitation.java
- src/main/java/ssafy/lambda/membership/entity/Membership.java
- src/main/java/ssafy/lambda/membership/service/MembershipService.java
- src/main/java/ssafy/lambda/membership/service/MembershipServiceImpl.java
- src/main/java/ssafy/lambda/notification/entity/NotificationDetail/InvitationNotification.java
- src/main/java/ssafy/lambda/team/service/TeamServiceImpl.java
- src/main/java/ssafy/lambda/vote/entity/Vote.java
team 안에서 닉네임을 변경했을때 중복체크하는 로직을 추가했습니다.
> fix: team 팀내 중복 닉네임 예외 체크

- src/main/java/ssafy/lambda/board/entity/ExpiredVote.java
- src/main/java/ssafy/lambda/board/repository/ExpiredVoteRepository.java
- src/main/java/ssafy/lambda/board/service/BoardServiceImpl.java
- src/main/java/ssafy/lambda/membership/entity/Membership.java
- src/main/java/ssafy/lambda/notification/entity/NotificationDetail/VoteNotification.java
- src/main/java/ssafy/lambda/vote/controller/VoteController.java
- src/main/java/ssafy/lambda/vote/entity/Vote.java
- src/main/java/ssafy/lambda/vote/entity/VoteInfo.java
- src/main/java/ssafy/lambda/vote/repository/VoteRepositoryImpl.java
- src/main/java/ssafy/lambda/vote/service/VoteServiceImpl.java
- vote와 expired_vote의 필드를 Membership에서 Team으로 변경했습니다
- team 삭제 시 연관된 vote와 vote_Info를 모두 삭제하는 로직을 추가했습니다
- 투표에는 투표를 생성한 멤버에 대한 정보를 저장하지 않습니다! 
- hibernate의 ddl-auto 확인 필요
> vote 필드 수정

- src/main/java/ssafy/lambda/invitation/controller/InvitationController.java
- src/main/java/ssafy/lambda/invitation/dto/RequestAcceptInvitationDto.java
- src/main/java/ssafy/lambda/invitation/repository/InvitationRepository.java
- src/main/java/ssafy/lambda/invitation/service/InvitationService.java
- src/main/java/ssafy/lambda/invitation/service/InvitationServiceImpl.java
Invitation 수락 API를  수정했습니다.  notificationId -> teamname
> Invitation 수락 API 수정 notificationId -> teamname
